spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:sl2genformback}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:root5710}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidationMustBeLongEnough123456}
  expiration: ${JWT_EXPIRATION:86400000}