INSERT INTO users (user_name, user_surname, user_email)
VALUES ('Igor Gomes', 'Leandro', 'igorgleandro@icloud.com');

INSERT INTO myforms (
    user_id,
    agent_name,
    agent_nbr,
    agency_name,
    agency_nbr,
    name_insured,
    description_risk,
    coverage_code,
    insurer1,
    contacted_through1,
    full_contact_name1,
    email_phone1,
    website1,
    naic1,
    date1,
    insurer2,
    contacted_through2,
    full_contact_name2,
    email_phone2,
    website2,
    naic2,
    date2,
    insurer3,
    contacted_through3,
    full_contact_name3,
    email_phone3,
    website3,
    naic3,
    date3
) VALUES (
             1,
             'Igor Gomes Leandro',
             '456',
             'gfjf',
             '12345',
             'Balthazar',
             'Homeowners',
             'undefined',
             '12963',
             'online',
             'Igor Gomes Leandro1',
             'igorgleandro@icloud.com',
             'website1',
             'NACI1',
             '2025-07',
             '12963',
             'email-phone',
             'Igor Gomes Leandro2',
             'igorgleandro@icloud.com',
             'web2',
             'Naic2',
             '2025-12',
             '33898',
             'online',
             'Igor Gomes Leandro3',
             'igorgleandro@icloud.com',
             'web3',
             'Naic3',
             '2025-11'
         );